spring:
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: mongodb+srv://lilchris:Chris123@cluster0-hnhd3.mongodb.net
      database: nbaDB
      

jwt:
  secret: nbamarket
server:
  port: 8080

  